apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-app
  template:
    metadata:
      labels:
        app: chat-app
    spec:
      containers:
        - name: chat-app
          image: karanpatel1006/chat-app:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: chat-db
              mountPath: "/var/www/html/chat.db"
              subPath: chat.db
      volumes:
        - name: chat-db
          persistentVolumeClaim:
            claimName: chat-db-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chat-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: chat-app-service
spec:
  selector:
    app: chat-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer